# /etc/fail2ban/jail.d/rem.conf
# Bloquea IPs que fallen en login repetidamente.

[rem-auth]
enabled  = true
port     = https,http
filter   = rem-auth
logpath  = /var/log/apache2/rem-access.log
maxretry = 5
findtime = 600
bantime  = 3600
action   = %(action_mwl)s
